### PR TITLE
Fix: wrong port loging

### PR DESCRIPTION
**Pull request by 13banda**
logging port is misleading: now fixed

### CODE REVIEW

**Comment by smashah** [comment]
I have 0 qualms merging this but what makes a port wrong or right?

**Comment by gnadelwartz** [comment]
because the Message print a different Port than actually used?

**Comment by SuryaMaulana** [comment]
because the Message print a different Port than actually used?(2)

**Comment by smashah** [comment]
Oops silly me I thought you were just changing the actual port used!

**Pull request merged**
